algoritmo "numeros inteiros"
// Função : Leitura de valores entre 1 e 10
// Autor : Simone Lemes
// Data : 29/10/2015
// Seção de Declarações 
var
   numero: inteiro
inicio
// Seção de Comandos
escreva ("Digite um valor:")
Leia (numero)
se (numero >10)ou(numero <1) entao
escreva ("O valor fornecido está fora da faixa permitida:")
        senao
        escreva ("O valor fornecido está  na faixa permitida")
     fimse

fimalgoritmo
