algoritmo "maior que 3"
// Função :  Apresentar somente maior que 3
// Autor : Simone Lemes
// Data : 29/10/2015
// Seção de Declarações 
var
    Numero: inteiro
inicio
// Seção de Comandos 
escreva ("valor de um numero: ")
Leia (numero)
se numero >3  entao
escreva (numero >3)
     senao
     se numero <3 entao
     escreva ("numero nao e maior que 3:")
             Fimse
             fimse
     

fimalgoritmo
